#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 236
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Ocarina"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "A3"
		release_rate = 186
		env_rate = [
			2, 229, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Inst_Piano_Low"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Inst_Piano_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Piano_Hi"
			tuning = 0.500000
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "G3"
		release_rate = 93
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Inst_Piano_Low"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Inst_Piano_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Piano_Hi"
			tuning = 0.500000

