#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Dark"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Synth_String"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Creek"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Creek"
			tuning = 1.000000
		[inst.entry.hi]
[drum]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.420448
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.445449
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.471937
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.500000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.529732
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.561231
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.594604
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.629961
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.667420
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.707107
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.749154
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.793701
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.840897
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.890899
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 0.943875
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 1.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Kick"
		tuning = 1.059463
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.059463
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.122462
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.189207
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.259921
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.334840
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.414214
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.498307
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.587401
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.681793
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.781798
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 1.887749
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.118926
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.244924
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.378414
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.519842
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.669680
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.828428
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 2.996615
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 3.174803
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 3.363586
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 3.563596
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 3.775498
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 4.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 4.237853
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 4.489849
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 4.756829
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 5.039685
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 5.339360
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 5.656855
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 5.993229
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 6.349606
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 6.727173
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 7.127192
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 7.550996
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 8.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 8.475705
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 8.979697
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 9.513658
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 10.079370
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 10.678720
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 11.313710
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 11.986459
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 12.699211
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 13.454346
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 64
		release_rate = 248
		sample = "Perc_Beat_Snare"
		tuning = 14.254383
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]

