#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 98
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cave"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "C5"
		release_rate = 93
		env_rate = [
			2, 298, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Inst_Shine_Dark"
			tuning = 1.498307
		[inst.entry.prim]
			sample = "Inst_Drone_Drip"
			tuning = 0.250000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G#4"
		release_rate = 186
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Inst_Choir_Male_Low"
			tuning = 0.974482
		[inst.entry.prim]
			sample = "Inst_Choir_Male_Prim"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "A3"
		release_rate = 186
		env_rate = [
			2, 229, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Inst_Piano_Low"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Inst_Piano_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Piano_Hi"
			tuning = 0.500000
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "G3"
		release_rate = 93
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Inst_Piano_Low"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Inst_Piano_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Piano_Hi"
			tuning = 0.500000
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 9
		env_rate = [
			2, 298, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Scream"
			tuning = 0.689062
		[inst.entry.hi]

