#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 93
		env_rate = [
			69, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Anim_Bird_Nightingale1"
			tuning = 1.334840
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 93
		env_rate = [
			24, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Anim_Bird_Nightingale1"
			tuning = 1.334840
		[inst.entry.hi]

